__include__: [
  '../runtime.yml',
  '../dataset/coco_detection.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
  '../cl_pipeline.yml'
]

output_dir: ./outputs/weights/
